import { test, expect } from "@playwright/test";
import { readFileSync, unlinkSync, writeFileSync, utimesSync } from "node:fs";
import { join } from "node:path";

test.use({ locale: "zh-CN" });

test("bilingual setup, real incremental build, state preservation and login", async ({ page }) => {
  test.setTimeout(120000);
  const root = process.env.MUSICFORGE_TEST_ROOT!;
  await expect.poll(async () => {
    try { return (await page.request.get("/healthz")).status(); } catch { return 0; }
  }).toBe(200);
  const log = readFileSync(join(root, "server.log"), "utf8");
  const code = JSON.parse(log.split("\n").find(line => line.includes('"setup_code"'))!).setup_code as string;
  await page.goto("/");
  await page.getByLabel("初始化码").fill(code);
  await page.getByLabel("用户名", { exact: true }).fill("admin");
  await page.getByLabel("密码", { exact: true }).fill("test-admin-password");
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.getByLabel("Setup code", { exact: true })).toHaveValue(code);
  await expect(page.getByLabel("Username", { exact: true })).toHaveValue("admin");
  await expect(page.getByLabel("Password", { exact: true })).toHaveValue("test-admin-password");
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("button", { name: "创建管理员" }).click();
  await expect(page.getByRole("heading", { name: "音乐，从母库到播放" })).toBeVisible();
  await page.getByRole("link", { name: "设置", exact: true }).click();
  await page.getByLabel("FLAC 源目录").fill(join(root, "source"));
  await page.getByLabel("转码输出目录").fill(join(root, "output"));
  await page.getByLabel("启用音乐库扫描和后台任务").check();
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByLabel("FLAC source directory", { exact: true })).toHaveValue(join(root, "source"));
  await expect(page.getByLabel("Enable library scanning and background jobs", { exact: true })).toBeChecked();
  await expect(page.getByRole("heading", { name: "Encoding profile" })).toBeVisible();
  await expect(page.getByText("VBR varies bitrate with audio complexity; CBR uses a fixed bitrate.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Bind your OIDC identity", exact: true })).toBeVisible();
  // The selector's native language names are intentionally not translated.
  await expect(page.locator(".page-content")).not.toContainText(/[\u3400-\u9fff]/);
  await page.getByRole("button", { name: "Save settings", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Settings saved");
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await expect(page.getByRole("status")).toContainText("设置已保存");
  await page.getByRole("link", { name: "音乐库", exact: true }).click();
  await expect(page.getByText("CI Track", { exact: true })).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole("table").getByText("已就绪", { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByLabel("搜索音乐库", { exact: true }).fill("CI Track");
  await page.getByLabel("状态筛选", { exact: true }).selectOption("ready");
  await page.getByLabel("选择 CI Track", { exact: true }).check();
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByLabel("Search library", { exact: true })).toHaveValue("CI Track");
  await expect(page.getByLabel("Filter by status", { exact: true })).toHaveValue("ready");
  await expect(page.getByLabel("Select CI Track", { exact: true })).toBeChecked();
  await expect(page.getByText("Selected: 1", { exact: true })).toBeVisible();
  await expect(page.getByRole("table").getByText("Ready", { exact: true })).toBeVisible();
  await expect(page.getByText("1 indexed track · Source and artifact status at a glance", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Delete selected expired artifacts", exact: true })).toBeDisabled();
  const sourcePath = join(root, "source/Artist/Album/01.flac");
  const sourceBytes = readFileSync(sourcePath);
  unlinkSync(sourcePath);
  await page.getByRole("button", { name: "Scan", exact: true }).click();
  await page.getByLabel("Filter by status", { exact: true }).selectOption("expired");
  await expect(page.getByText("Source deleted", { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByLabel("Select CI Track", { exact: true }).check();
  let confirmation = page.waitForEvent("dialog");
  let clicking = page.getByRole("button", { name: "Delete selected expired artifacts", exact: true }).click();
  let dialog = await confirmation;
  expect(dialog.message()).toBe("Permanently delete expired artifacts among the selected tracks?");
  await dialog.dismiss();
  await clicking;
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  confirmation = page.waitForEvent("dialog");
  clicking = page.getByRole("button", { name: "删除所选过期产物", exact: true }).click();
  dialog = await confirmation;
  expect(dialog.message()).toBe("永久删除所选歌曲中的过期产物？");
  await dialog.dismiss();
  await clicking;
  writeFileSync(sourcePath, sourceBytes);
  const stable = new Date(Date.now() - 120000);
  utimesSync(sourcePath, stable, stable);
  await page.getByRole("button", { name: "扫描", exact: true }).click();
  await page.getByLabel("状态筛选", { exact: true }).selectOption("ready");
  await expect(page.getByRole("table").getByText("已就绪", { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByRole("link", { name: "概览", exact: true }).click();
  await expect(page.getByText("100%", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/dashboard-zh-CN.png", fullPage: true });
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByText("1 track matches the current profile", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/dashboard-en.png", fullPage: true });
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("link", { name: "任务", exact: true }).click();
  await expect(page.getByRole("heading", { name: "后台任务" })).toBeVisible();
  await page.getByRole("button", { name: "详情", exact: true }).first().click();
  await expect(page.getByText("任务日志", { exact: true })).toBeVisible();
  const rawLog = await page.locator(".task-details pre").last().textContent();
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByText("Job logs", { exact: true })).toBeVisible();
  await expect(page.locator(".task-details pre").last()).toHaveText(rawLog === "任务成功完成。" ? "Job completed successfully." : rawLog!);
  await page.reload();
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.getByRole("heading", { name: "Background jobs" })).toBeVisible();
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("button", { name: "退出登录" }).click();
  await expect(page.getByRole("heading", { name: "欢迎回来" })).toBeVisible();
  await page.getByLabel("用户名", { exact: true }).fill("admin");
  await page.getByLabel("密码", { exact: true }).fill("wrong-password");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("alert")).toHaveText("用户名或密码错误");
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByRole("alert")).toHaveText("invalid username or password");
  await expect(page.getByLabel("Username", { exact: true })).toHaveValue("admin");
  await page.getByLabel("Password", { exact: true }).fill("test-admin-password");
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("heading", { name: "后台任务" })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("button", { name: "退出登录", exact: true })).toBeVisible();
  await page.getByRole("link", { name: "概览", exact: true }).click();
  await expect(page.getByRole("progressbar")).toHaveAttribute("aria-valuenow", "100");
  await page.screenshot({ path: "test-results/mobile-dashboard-zh-CN.png", fullPage: true });
  await page.route("**/api/dashboard", route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "database unavailable" }) }));
  await expect(page.getByRole("alert")).toContainText("暂时无法获取更新", { timeout: 15000 });
  await expect(page.getByText("100%", { exact: true })).toBeVisible();
  await page.unroute("**/api/dashboard");
  await page.getByRole("button", { name: "重试", exact: true }).click();
  await expect(page.getByRole("alert")).not.toBeVisible();
  await page.getByRole("link", { name: "设置", exact: true }).click();
  await expect(page.getByRole("button", { name: "保存设置", exact: true })).toBeDisabled();
  await page.getByLabel("同时转换数量", { exact: true }).fill("2");
  await expect(page.getByText("有未保存的更改", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByLabel("Concurrent conversions", { exact: true })).toHaveValue("2");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  const encodingTitle = await page.getByRole("heading", { name: "Encoding profile", exact: true }).boundingBox();
  expect(encodingTitle?.width).toBeGreaterThan(120);
  await page.screenshot({ path: "test-results/mobile-settings-en.png", fullPage: true });
  await page.screenshot({ path: "test-results/mobile-settings-viewport-en.png" });
  await page.getByLabel("Lidarr source path prefix", { exact: true }).fill("relative/flac");
  await page.getByRole("button", { name: "Save settings", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("Lidarr path prefix must be an absolute container path");
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await expect(page.getByRole("alert")).toContainText("Lidarr 路径前缀必须是容器内的绝对路径");
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await page.getByLabel("Lidarr source path prefix", { exact: true }).fill("/lidarr/flac");
  // Configure secrets with workers paused; these settings do not call remote services.
  await page.getByLabel("Enable library scanning and background jobs", { exact: true }).uncheck();
  await page.getByLabel("Navidrome URL", { exact: true }).fill("https://navidrome.example.test");
  await page.getByLabel("Navidrome username", { exact: true }).fill("admin");
  await page.getByLabel("Navidrome password", { exact: true }).fill("navidrome-test-secret");
  await page.getByLabel("Issuer URL", { exact: true }).fill("https://issuer.example.test");
  await page.getByLabel("Client ID", { exact: true }).fill("client");
  await page.getByLabel("Client Secret", { exact: true }).fill("oidc-test-secret");
  await page.getByRole("button", { name: "Save settings", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Settings saved");
  await expect(page.getByLabel("Navidrome password", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Delete the saved Navidrome password", { exact: true })).toBeDisabled();
  await expect(page.getByLabel("Delete the saved OIDC client secret", { exact: true })).toBeDisabled();
  await page.getByLabel("Navidrome URL", { exact: true }).fill("");
  await page.getByLabel("Issuer URL", { exact: true }).fill("");
  await page.getByLabel("Delete the saved Navidrome password", { exact: true }).check();
  await page.getByLabel("Delete the saved OIDC client secret", { exact: true }).check();
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await expect(page.getByLabel("删除已保存的 Navidrome 密码", { exact: true })).toBeChecked();
  await expect(page.getByLabel("删除已保存的 OIDC 客户端密钥", { exact: true })).toBeChecked();
  await page.getByRole("button", { name: "保存设置", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("设置已保存");
  await expect(page.getByLabel("删除已保存的 Navidrome 密码", { exact: true })).toBeDisabled();
  await expect(page.getByLabel("删除已保存的 Navidrome 密码", { exact: true })).not.toBeChecked();
  await expect(page.getByLabel("删除已保存的 OIDC 客户端密钥", { exact: true })).toBeDisabled();
  const cleared = await page.request.get("/api/settings");
  expect((await cleared.json()).configured).toMatchObject({ nav_password: false, oidc_secret: false });
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  // A second host reaches the same instance without sharing the primary host's cookie.
  const primaryOrigin = new URL(page.url()).origin;
  const aliasOrigin = "http://localhost:8787";
  expect((await page.context().cookies(aliasOrigin)).find(cookie => cookie.name === "musicforge_session")).toBeUndefined();
  const aliasPage = await page.context().newPage();
  await aliasPage.goto(`${aliasOrigin}/settings`);
  await expect(aliasPage.getByRole("heading", { name: "欢迎回来" })).toBeVisible();
  await aliasPage.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await aliasPage.getByLabel("Username", { exact: true }).fill("admin");
  await aliasPage.getByLabel("Password", { exact: true }).fill("test-admin-password");
  await aliasPage.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(aliasPage.getByRole("textbox", { name: "Allowed access URLs", exact: true })).toHaveValue(`${primaryOrigin}\n${aliasOrigin}`);
  await expect(aliasPage.getByLabel("Callback URL", { exact: true })).toHaveValue(`${primaryOrigin}/api/auth/oidc/callback`);
  await expect(aliasPage.getByRole("button", { name: "Bind your OIDC identity", exact: true })).toBeDisabled();
  await expect(aliasPage.getByRole("link", { name: "Open primary URL", exact: true })).toHaveAttribute("href", `${primaryOrigin}/settings`);
  const aliasCookie = (await page.context().cookies(aliasOrigin)).find(cookie => cookie.name === "musicforge_session")!;
  expect(aliasCookie.domain).toBe("localhost");
  expect(aliasCookie.httpOnly).toBe(true);
  expect(aliasCookie.secure).toBe(false);
  await aliasPage.getByLabel("Concurrent conversions", { exact: true }).fill("3");
  await aliasPage.getByRole("button", { name: "Save settings", exact: true }).click();
  await expect(aliasPage.getByRole("status")).toContainText("Settings saved");
  expect((await (await page.request.get("/api/settings")).json()).settings.concurrency).toBe(3);
  await aliasPage.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await expect(aliasPage.getByRole("textbox", { name: "允许访问的地址", exact: true })).toHaveValue(`${primaryOrigin}\n${aliasOrigin}`);
  await expect(aliasPage.getByText("绑定 OIDC 身份前，请在主地址使用本地管理员账号登录。")).toBeVisible();
  const oidcRedirect = await aliasPage.request.get(`${aliasOrigin}/api/auth/oidc/login?return_to=https://evil.test`, { maxRedirects: 0 });
  expect(oidcRedirect.status()).toBe(303);
  expect(oidcRedirect.headers().location).toBe(`${primaryOrigin}/api/auth/oidc/login`);
  expect(oidcRedirect.headers()["set-cookie"]).toBeUndefined();
  const aliasMe = await (await aliasPage.request.get(`${aliasOrigin}/api/auth/me`)).json();
  const blocked = await aliasPage.request.post(`${aliasOrigin}/api/auth/logout`, {
    data: {}, headers: { Origin: "http://unconfigured.test", "X-CSRF-Token": aliasMe.csrf },
  });
  expect(blocked.status()).toBe(403);
  await aliasPage.getByRole("button", { name: "退出登录", exact: true }).click();
  await expect(aliasPage.getByRole("heading", { name: "欢迎回来" })).toBeVisible();
  expect((await (await page.request.get("/api/auth/me")).json()).authenticated).toBe(true);
  await aliasPage.close();
  await page.getByRole("button", { name: "Log out", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Welcome back" })).toBeVisible();
});
