import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

test.use({ locale: "zh-CN" });

test("bilingual setup, real incremental build, state preservation and login", async ({ page }) => {
  const root = process.env.MUSICFORGE_TEST_ROOT!;
  await expect.poll(async () => {
    try { return (await page.request.get("/healthz")).status(); } catch { return 0; }
  }).toBe(200);
  const log = readFileSync(join(root, "server.log"), "utf8");
  const code = JSON.parse(log.split("\n").find(line => line.includes('"setup_code"'))!).setup_code as string;
  await page.goto("/");
  await page.getByLabel("初始化码").fill(code);
  await page.getByLabel("用户名", { exact: true }).fill("admin");
  await page.getByLabel("密码", { exact: true }).fill("test-admin-password");
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.getByLabel("Setup code", { exact: true })).toHaveValue(code);
  await expect(page.getByLabel("Username", { exact: true })).toHaveValue("admin");
  await expect(page.getByLabel("Password", { exact: true })).toHaveValue("test-admin-password");
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("button", { name: "创建管理员" }).click();
  await expect(page.getByRole("heading", { name: "音乐，从母库到播放" })).toBeVisible();
  await page.getByRole("link", { name: "设置", exact: true }).click();
  await page.getByLabel("FLAC 源目录").fill(join(root, "source"));
  await page.getByLabel("转码输出目录").fill(join(root, "output"));
  await page.getByLabel("启用音乐库扫描和后台任务").check();
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByLabel("FLAC source directory", { exact: true })).toHaveValue(join(root, "source"));
  await expect(page.getByLabel("Enable library scanning and background jobs", { exact: true })).toBeChecked();
  await expect(page.getByRole("heading", { name: "Encoding profile" })).toBeVisible();
  await expect(page.getByText("VBR varies bitrate with audio complexity; CBR uses a fixed bitrate.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Bind your OIDC identity", exact: true })).toBeVisible();
  // The selector's native language names are intentionally not translated.
  await expect(page.locator(".page-content")).not.toContainText(/[\u3400-\u9fff]/);
  await page.getByRole("button", { name: "Save settings", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Settings saved");
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await expect(page.getByRole("status")).toContainText("设置已保存");
  await page.getByRole("link", { name: "音乐库", exact: true }).click();
  await expect(page.getByText("CI Track", { exact: true })).toBeVisible({ timeout: 30000 });
  await expect(page.getByRole("table").getByText("已就绪", { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByLabel("搜索音乐库", { exact: true }).fill("CI Track");
  await page.getByLabel("状态筛选", { exact: true }).selectOption("ready");
  await page.getByLabel("选择 CI Track", { exact: true }).check();
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByLabel("Search library", { exact: true })).toHaveValue("CI Track");
  await expect(page.getByLabel("Filter by status", { exact: true })).toHaveValue("ready");
  await expect(page.getByLabel("Select CI Track", { exact: true })).toBeChecked();
  await expect(page.getByText("Selected: 1", { exact: true })).toBeVisible();
  await expect(page.getByRole("table").getByText("Ready", { exact: true })).toBeVisible();
  await expect(page.getByText("1 indexed track · Source and artifact status at a glance", { exact: true })).toBeVisible();
  let confirmation = page.waitForEvent("dialog");
  let clicking = page.getByRole("button", { name: "Delete selected expired artifacts", exact: true }).click();
  let dialog = await confirmation;
  expect(dialog.message()).toBe("Permanently delete expired artifacts among the selected tracks?");
  await dialog.dismiss();
  await clicking;
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  confirmation = page.waitForEvent("dialog");
  clicking = page.getByRole("button", { name: "删除所选过期产物", exact: true }).click();
  dialog = await confirmation;
  expect(dialog.message()).toBe("永久删除所选歌曲中的过期产物？");
  await dialog.dismiss();
  await clicking;
  await page.getByRole("link", { name: "概览", exact: true }).click();
  await expect(page.getByText("100%", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/dashboard-zh-CN.png", fullPage: true });
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByText("1 track matches the current profile", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/dashboard-en.png", fullPage: true });
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("link", { name: "任务", exact: true }).click();
  await expect(page.getByRole("heading", { name: "后台任务" })).toBeVisible();
  await page.getByRole("button", { name: "详情", exact: true }).first().click();
  await expect(page.getByText("任务日志", { exact: true })).toBeVisible();
  const rawLog = await page.locator(".task-details pre").last().textContent();
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByText("Job logs", { exact: true })).toBeVisible();
  await expect(page.locator(".task-details pre").last()).toHaveText(rawLog === "任务成功完成。" ? "Job completed successfully." : rawLog!);
  await page.reload();
  await expect(page.locator("html")).toHaveAttribute("lang", "en");
  await expect(page.getByRole("heading", { name: "Background jobs" })).toBeVisible();
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("button", { name: "退出登录" }).click();
  await expect(page.getByRole("heading", { name: "欢迎回来" })).toBeVisible();
  await page.getByLabel("用户名", { exact: true }).fill("admin");
  await page.getByLabel("密码", { exact: true }).fill("wrong-password");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("alert")).toHaveText("用户名或密码错误");
  await page.getByRole("combobox", { name: "语言", exact: true }).selectOption("en");
  await expect(page.getByRole("alert")).toHaveText("invalid username or password");
  await expect(page.getByLabel("Username", { exact: true })).toHaveValue("admin");
  await page.getByLabel("Password", { exact: true }).fill("test-admin-password");
  await page.getByRole("combobox", { name: "Language", exact: true }).selectOption("zh-CN");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("heading", { name: "后台任务" })).toBeVisible();
});
