import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Activity, ArrowDownToLine, ArrowRight, Check, ChevronLeft, ChevronRight, Clock3, Disc3, FolderOpen, HardDrive, LayoutDashboard, ListMusic, Loader2, LogOut, Music2, Play, RefreshCw, Search, Settings2, ShieldCheck, Trash2, Waves } from "lucide-react";
import { Button } from "./components/ui/button";
import { api, setCSRF } from "./api";
import type { Dashboard, Job, Me, Settings, Source } from "./types";
import { LanguageSelector, useI18n, type MessageKey } from "./i18n";

type Notice = (message: MessageKey | Error, error?: boolean) => void;

function useResource<T>(path: string, poll = false) {
  const [data, setData] = useState<T>();
  const [error, setError] = useState("");
  useEffect(() => {
    let alive = true;
    const load = () => api<T>(path).then(value => { if (alive) { setData(value); setError(""); } }).catch(err => { if (alive) setError(String(err.message)); });
    void load();
    const timer = poll ? setInterval(load, 5000) : undefined;
    return () => { alive = false; clearInterval(timer); };
  }, [path, poll]);
  return { data, error };
}
function Badge({ status }: { status: string }) { const { status: label } = useI18n(); return <span className={`badge badge-${status}`}><span />{label(status)}</span>; }
function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="empty"><Disc3 size={36} strokeWidth={1.2} /><h3>{title}</h3><p>{children}</p></div>; }
function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <div className="field"><label className="field-label"><span>{label}</span>{children}</label>{hint && <small>{hint}</small>}</div>; }
function Loading({ error }: { error?: string }) { const { t, errorMessage } = useI18n(); return <div className="empty">{error ? <p role="alert">{errorMessage(error)}</p> : <Loader2 className="animate-spin" role="status" aria-label={t("app.loading")} />}</div>; }

export function App() {
  const { t, errorMessage } = useI18n();
  const [me, setMe] = useState<Me>();
  const [authError, setAuthError] = useState("");
  const [page, setPage] = useState(location.pathname);
  const [toast, setToast] = useState<{ message: MessageKey | Error; error: boolean }>();
  const notify: Notice = (message, error = false) => setToast({ message, error });
  const loadMe = () => api<Me>("/auth/me").then(value => { setCSRF(value.csrf || ""); setMe(value); setAuthError(""); }).catch(err => setAuthError(err.message));
  useEffect(() => {
    void loadMe();
    const pop = () => setPage(location.pathname);
    const expired = () => { setMe(undefined); void loadMe(); };
    window.addEventListener("popstate", pop); window.addEventListener("session-expired", expired);
    return () => { window.removeEventListener("popstate", pop); window.removeEventListener("session-expired", expired); };
  }, []);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(undefined), 6000); return () => clearTimeout(timer); } }, [toast]);
  function navigate(path: string) { history.pushState(null, "", path); setPage(path); window.scrollTo(0, 0); }
  if (!me) return <div className="auth-layout"><LanguageSelector /><Loading error={authError} />{authError && <Button onClick={() => void loadMe()}>{t("app.reconnect")}</Button>}</div>;
  if (!me.authenticated) return <Auth me={me} done={loadMe} />;
  const nav = [{ path: "/", label: t("app.overview"), icon: LayoutDashboard }, { path: "/library", label: t("app.library"), icon: ListMusic }, { path: "/jobs", label: t("app.jobs"), icon: Activity }, { path: "/settings", label: t("app.settings"), icon: Settings2 }];
  const current = nav.find(item => item.path === page) || nav[0];
  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="/" onClick={e => { e.preventDefault(); navigate("/"); }}><span className="brand-icon"><Waves /></span><span>MusicForge<small>{t("app.tagline")}</small></span></a>
      <span className="nav-caption">{t("app.workspace")}</span>
      <nav aria-label={t("app.navigation")}>{nav.map(item => <a key={item.path} href={item.path} className={current.path === item.path ? "active" : ""} onClick={e => { e.preventDefault(); navigate(item.path); }}><item.icon size={19} />{item.label}{current.path === item.path && <span className="nav-dot" />}</a>)}</nav>
      <div className="sidebar-bottom"><div className="single-host"><HardDrive size={16} /><span>{t("app.singleHost")}<small>{me.version}</small></span></div><div className="account"><span className="avatar">{me.username?.slice(0, 1).toUpperCase()}</span><span>{me.username}<small>{me.method === "oidc" ? t("app.oidcAdmin") : t("app.localAdmin")}</small></span><Button variant="ghost" size="icon" aria-label={t("app.logout")} onClick={() => void api("/auth/logout", "POST", {}).then(loadMe).catch(err => notify(err as Error, true))}><LogOut size={17} /></Button></div></div>
    </aside>
    <main className="main"><header className="topbar"><span>{t("app.workspace")}<ChevronRight size={14} /> <strong>{current.label}</strong></span><div className="topbar-actions"><LanguageSelector /><span className="topbar-note"><ShieldCheck size={15} />{t("app.session")}</span></div></header>
      <div className="page-content">{page === "/library" ? <Library notify={notify} /> : page === "/jobs" ? <Jobs notify={notify} /> : page === "/settings" ? <SettingsPage me={me} notify={notify} /> : <Overview notify={notify} navigate={navigate} />}</div>
    </main>
    {toast && <div className={`toast ${toast.error ? "toast-error" : ""}`} role={toast.error ? "alert" : "status"}>{toast.error ? <Activity size={17} /> : <Check size={17} />}{toast.message instanceof Error ? errorMessage(toast.message.message) : t(toast.message)}<button aria-label={t("app.dismiss")} onClick={() => setToast(undefined)}>×</button></div>}
  </div>;
}

function Auth({ me, done }: { me: Me; done: () => Promise<void> }) {
  const { t, errorMessage } = useI18n();
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const setup = !me.initialized;
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(""); const form = new FormData(e.currentTarget); try { await api(`/auth/${setup ? "setup" : "login"}`, "POST", { username: form.get("username"), password: form.get("password"), ...(setup ? { code: form.get("code") } : {}) }); await done(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  return <div className="auth-layout"><LanguageSelector /><div className="auth-art" aria-hidden="true">{Array.from({ length: 29 }, (_, i) => <span key={i} style={{ height: `${20 + Math.sin(i * 1.7) ** 2 * 130}px` }} />)}</div><div className="auth-card"><div className="auth-logo"><Waves size={30} /> MusicForge</div><span className="eyebrow">{t("auth.eyebrow")}</span><h1>{setup ? t("auth.setupTitle") : t("auth.loginTitle")}</h1><p>{setup ? t("auth.setupDescription") : t("auth.loginDescription")}</p>
    <form onSubmit={submit}>{setup && <Field label={t("auth.code")}><input name="code" required autoComplete="off" placeholder={t("auth.codePlaceholder")} /></Field>}<Field label={t("auth.username")}><input name="username" required autoComplete="username" maxLength={100} /></Field><Field label={t("auth.password")} hint={setup ? t("auth.passwordHint") : undefined}><input name="password" type="password" required autoComplete={setup ? "new-password" : "current-password"} /></Field>{error && <div className="error-box" role="alert">{errorMessage(error)}</div>}<Button className="w-full" disabled={busy}>{busy ? <Loader2 size={16} className="animate-spin" /> : <ArrowRight size={16} />}{setup ? t("auth.create") : t("auth.login")}</Button></form>{!setup && me.oidc && <Button className="mt-3 w-full" variant="outline" asChild><a href="/api/auth/oidc/login"><ShieldCheck size={17} />{t("auth.oidc")}</a></Button>}<small className="auth-footer">{t("auth.footer")}</small></div></div>;
}

function Overview({ notify, navigate }: { notify: Notice; navigate: (path: string) => void }) {
  const { t, kind, date, number, errorMessage, locale } = useI18n();
  const { data, error } = useResource<Dashboard>("/dashboard", true);
  const jobs = useResource<{ jobs: Job[] }>("/jobs?limit=5", true);
  const config = useResource<{ settings: Settings }>("/settings");
  const [busy, setBusy] = useState(false);
  async function scan() { setBusy(true); try { await api("/library/scan", "POST", {}); notify("notice.scan"); } catch (err) { notify(err as Error, true); } finally { setBusy(false); } }
  if (!data) return <Loading error={error} />;
  const percent = data.source_count ? Math.round(data.ready_count / data.source_count * 100) : 0;
  const metrics = [{ label: t("overview.sources"), value: data.source_count, icon: Disc3, note: t("overview.masters") }, { label: t("overview.outputs"), value: data.output_count, icon: Music2, note: t("overview.outputLibrary", { codec: data.codec.toUpperCase() }) }, { label: t("overview.complete"), value: new Intl.NumberFormat(locale, { style: "percent" }).format(percent / 100), icon: Check, note: t("overview.readyCount", { count: data.ready_count }) }, { label: t("overview.attention"), value: data.expired_count + data.rebuild_count, icon: Clock3, note: t("overview.attentionCounts", { rebuild: data.rebuild_count, expired: data.expired_count }) }];
  return <><div className="page-heading"><div><span className="eyebrow">{t("overview.eyebrow")}</span><h1>{t("overview.title")}</h1><p>{t("overview.description")}</p></div><Button onClick={() => void scan()} disabled={busy || !data.enabled}><RefreshCw size={16} className={busy ? "animate-spin" : ""} />{t("overview.scan")}</Button></div>
    {!data.online && <div className="banner"><HardDrive size={20} /><div><strong>{data.enabled ? t("overview.offline") : t("overview.configure")}</strong><p>{errorMessage(data.storage_message)}</p></div><Button variant="outline" size="sm" onClick={() => navigate("/settings")}>{t("overview.openSettings")}</Button></div>}
    {data.rebuild_count > 0 && <div className="banner"><RefreshCw size={20} /><div><strong>{t("overview.rebuildCount", { count: data.rebuild_count })}</strong><p>{t("overview.keepPlayable")}</p></div><Button variant="outline" size="sm" onClick={() => navigate("/library")}>{t("overview.viewLibrary")}</Button></div>}
    <div className="metrics">{metrics.map(metric => <div className="metric" key={metric.label}><div><span>{metric.label}</span><metric.icon size={19} /></div><strong>{typeof metric.value === "number" ? number(metric.value) : metric.value}</strong><small>{metric.note}</small></div>)}</div>
    <div className="panel pipeline"><div className="panel-heading"><div><h2>{t("overview.pipeline")}</h2><p>{t("overview.pipelineDescription")}</p></div><span className={`online ${data.online ? "is-online" : ""}`}><span />{data.online ? t("overview.online") : t("overview.waiting")}</span></div><div className="pipeline-flow"><div><Disc3 /><small>{t("overview.sourceEyebrow")}</small><h3>{t("overview.flac")}</h3><code>{config.data?.settings.source || "—"}</code></div><ArrowRight className="flow-arrow" /><div className="pipeline-forge"><Waves /><small>{t("overview.buildEyebrow")}</small><h3>MusicForge</h3><span>ffmpeg · {data.codec.toUpperCase()}</span></div><ArrowRight className="flow-arrow" /><div><ArrowDownToLine /><small>{t("overview.outputEyebrow")}</small><h3>{t("overview.streaming")}</h3><code>{config.data?.settings.output || "—"}</code></div></div><div className="build-progress"><span>{t("overview.currentProfile")}</span><span>{number(data.ready_count)} / {number(data.source_count)}</span><div><span style={{ width: `${percent}%` }} /></div></div></div>
    <div className="panel"><div className="panel-heading"><div><h2>{t("overview.recent")}</h2><p>{t("overview.background")}</p></div><Button variant="ghost" size="sm" onClick={() => navigate("/jobs")}>{t("overview.allJobs")}<ArrowRight size={14} /></Button></div>{jobs.data?.jobs.length ? <div className="job-list">{jobs.data.jobs.map(job => <div className="job-row" key={job.id}><span className={`job-symbol ${job.state}`}><Activity size={18} /></span><div><strong>{kind(job.kind)}</strong><small>{t("overview.job", { id: String(job.id), date: date(job.updated) })}</small></div><Badge status={job.state} /></div>)}</div> : <Empty title={t("overview.noJobs")}>{t("overview.noJobsHint")}</Empty>}</div>
  </>;
}

function Library({ notify }: { notify: Notice }) {
  const { t, status: statusLabel } = useI18n();
  const { data, error } = useResource<Source[]>("/library", true);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState<Set<number>>(new Set()); const [busy, setBusy] = useState(false); const [offset, setOffset] = useState(0);
  async function action(path: string, body: unknown, message: MessageKey) { setBusy(true); try { await api(path, "POST", body); notify(message); setSelected(new Set()); } catch (err) { notify(err as Error, true); } finally { setBusy(false); } }
  if (!data) return <Loading error={error} />;
  const rows = data.filter(source => (filter === "all" || source.status === filter) && `${source.artist} ${source.album} ${source.title} ${source.path}`.toLowerCase().includes(query.toLowerCase()));
  const shown = rows.slice(offset, offset + 50); const expired = data.filter(s => !s.present && s.output).length;
  function toggle(id: number) { setSelected(old => { const value = new Set(old); if (value.has(id)) value.delete(id); else value.add(id); return value; }); }
  function deleteSelected(all: boolean) { if (window.confirm(all ? t("library.deleteAllConfirm", { count: expired }) : t("library.deleteSelectedConfirm"))) void action("/library/delete", { all, ids: [...selected] }, "notice.delete"); }
  return <><div className="page-heading"><div><span className="eyebrow">{t("library.eyebrow")}</span><h1>{t("app.library")}</h1><p>{t("library.description", { count: data.length })}</p></div><div className="actions"><Button variant="outline" disabled={busy} onClick={() => void action("/library/scan", { verify: true }, "notice.verify")}><ShieldCheck size={16} />{t("library.verify")}</Button><Button disabled={busy} onClick={() => void action("/library/scan", {}, "notice.scan")}><RefreshCw size={16} />{t("library.scan")}</Button></div></div>
    {expired > 0 && <div className="banner amber"><Clock3 size={20} /><div><strong>{t("library.expiredCount", { count: expired })}</strong><p>{t("library.expiredHint")}</p></div><Button variant="destructive" size="sm" disabled={busy} onClick={() => deleteSelected(true)}>{t("library.deleteExpired")}</Button></div>}
    <div className="panel"><div className="table-toolbar"><div className="search"><Search size={17} /><input aria-label={t("library.search")} placeholder={t("library.searchPlaceholder")} value={query} onChange={e => { setQuery(e.target.value); setOffset(0); }} /></div><select aria-label={t("library.filter")} value={filter} onChange={e => { setFilter(e.target.value); setOffset(0); }}><option value="all">{t("library.allStatuses")}</option>{["ready", "needs_rebuild", "expired", "missing", "changed", "failed"].map(status => <option value={status} key={status}>{statusLabel(status)}</option>)}</select><Button variant="outline" size="sm" disabled={busy} onClick={() => void action("/library/rebuild", { all: true }, "notice.rebuild")}><Play size={14} />{t("library.startRebuild")}</Button></div>
      {selected.size > 0 && <div className="selection-bar"><span>{t("library.selected", { count: selected.size })}</span><Button size="sm" variant="outline" disabled={busy} onClick={() => void action("/library/rebuild", { ids: [...selected] }, "notice.selectedBuild")}>{t("library.buildSelected")}</Button><Button size="sm" variant="destructive" disabled={busy} onClick={() => deleteSelected(false)}><Trash2 size={13} />{t("library.deleteSelected")}</Button><Button size="sm" variant="ghost" onClick={() => setSelected(new Set())}>{t("library.clearSelection")}</Button></div>}
      {rows.length ? <><div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label={t("library.selectPage")} checked={shown.length > 0 && shown.every(s => selected.has(s.id))} onChange={e => setSelected(old => { const value = new Set(old); shown.forEach(s => e.target.checked ? value.add(s.id) : value.delete(s.id)); return value; })} /></th><th>{t("library.trackFile")}</th><th>{t("library.artistAlbum")}</th><th>{t("library.source")}</th><th>{t("library.artifact")}</th></tr></thead><tbody>{shown.map(source => <tr key={source.id} className={selected.has(source.id) ? "selected" : ""}><td><input type="checkbox" aria-label={t("library.selectTrack", { title: source.title || source.path })} checked={selected.has(source.id)} onChange={() => toggle(source.id)} /></td><td><div className="track-cell"><span className="track-number">{source.track || <Music2 size={15} />}</span><div><strong>{source.title || source.path.split("/").pop()}</strong><small title={source.path}>{source.path}</small></div></div></td><td><strong>{source.artist || t("library.unknownArtist")}</strong><small>{source.album || t("library.unknownAlbum")}</small></td><td><span className={source.present ? "source-present" : "source-missing"}>{source.present ? t("library.sourceOnline") : t("library.sourceDeleted")}</span></td><td><Badge status={source.status} />{source.output_present && source.status !== "ready" && <small>{t("library.stillPlayable")}</small>}{source.error && <details><summary>{t("library.errorDetails")}</summary><pre>{source.error}</pre></details>}</td></tr>)}</tbody></table></div><div className="pagination"><span>{t("library.pagination", { start: offset + 1, end: Math.min(offset + 50, rows.length), total: rows.length })}</span><Button variant="ghost" size="icon" aria-label={t("library.previous")} disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}><ChevronLeft size={16} /></Button><Button variant="ghost" size="icon" aria-label={t("library.next")} disabled={offset + 50 >= rows.length} onClick={() => setOffset(offset + 50)}><ChevronRight size={16} /></Button></div></> : <Empty title={data.length ? t("library.noMatch") : t("library.empty")}>{data.length ? t("library.noMatchHint") : t("library.emptyHint")}</Empty>}
    </div></>;
}

function Jobs({ notify }: { notify: Notice }) {
  const { t, status, kind, date } = useI18n();
  const [offset, setOffset] = useState(0); const [filter, setFilter] = useState("all"); const [expanded, setExpanded] = useState<number>(); const [selected, setSelected] = useState<Set<number>>(new Set());
  const { data, error } = useResource<{ jobs: Job[]; total: number }>(`/jobs?offset=${offset}&limit=100`, true);
  async function retry(ids?: number[]) { try { await api("/jobs/retry", "POST", ids ? { ids } : { all: true }); notify("notice.retry"); setSelected(new Set()); } catch (err) { notify(err as Error, true); } }
  if (!data) return <Loading error={error} />;
  const shown = data.jobs.filter(job => filter === "all" || job.state === filter);
  return <><div className="page-heading"><div><span className="eyebrow">{t("jobs.eyebrow")}</span><h1>{t("jobs.title")}</h1><p>{t("jobs.description")}</p></div><Button variant="outline" onClick={() => void retry()}><RefreshCw size={16} />{t("jobs.retryAll")}</Button></div><div className="panel"><div className="table-toolbar"><div className="filter-tabs">{["all", "pending", "running", "success", "failed"].map(state => <button key={state} className={filter === state ? "active" : ""} onClick={() => setFilter(state)}>{state === "all" ? t("jobs.all") : status(state)}</button>)}</div>{selected.size > 0 && <Button size="sm" onClick={() => void retry([...selected])}>{t("jobs.retrySelected", { count: selected.size })}</Button>}</div>{shown.length ? <div className="task-list">{shown.map(job => <div className="task" key={job.id}><div className="task-main"><input type="checkbox" aria-label={t("jobs.selectFailed", { id: String(job.id) })} disabled={job.state !== "failed"} checked={selected.has(job.id)} onChange={e => setSelected(old => { const value = new Set(old); e.target.checked ? value.add(job.id) : value.delete(job.id); return value; })} /><span className={`job-symbol ${job.state}`}>{job.state === "running" ? <Loader2 className="animate-spin" size={18} /> : <Activity size={18} />}</span><div className="task-description"><strong>{kind(job.kind)} <span>#{job.id}</span></strong><small>{job.args.id ? t("jobs.track", { id: String(job.args.id) }) : ""}{date(job.updated)}{t("jobs.attempts", { count: job.attempts })}</small></div><Badge status={job.state} /><Button variant="ghost" size="sm" onClick={() => setExpanded(expanded === job.id ? undefined : job.id)}>{expanded === job.id ? t("jobs.collapse") : t("jobs.details")}</Button>{job.state === "failed" && <Button variant="outline" size="sm" onClick={() => void retry([job.id])}>{t("jobs.retry")}</Button>}</div>{expanded === job.id && <div className="task-details"><p>{t("jobs.args")}</p><pre>{JSON.stringify(job.args, null, 2)}</pre><p>{t("jobs.logs")}</p><pre>{job.log || (job.state === "success" ? t("jobs.completed") : job.state === "running" ? t("jobs.processing") : t("jobs.waiting"))}</pre></div>}</div>)}</div> : <Empty title={t("jobs.empty")}>{t("jobs.emptyHint")}</Empty>}<div className="pagination"><span>{t("jobs.total", { count: data.total })}</span><Button variant="ghost" size="icon" aria-label={t("jobs.previous")} disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 100))}><ChevronLeft size={16} /></Button><Button variant="ghost" size="icon" aria-label={t("jobs.next")} disabled={offset + 100 >= data.total} onClick={() => setOffset(offset + 100)}><ChevronRight size={16} /></Button></div></div></>;
}

type SettingsResponse = { settings: Settings; configured: { webhook: boolean; nav_password: boolean; oidc_secret: boolean }; public_url: string };
function SettingsPage({ me, notify }: { me: Me; notify: Notice }) {
  const { t } = useI18n();
  const { data, error } = useResource<SettingsResponse>("/settings");
  const [settings, setSettings] = useState<Settings>(); const [busy, setBusy] = useState(false); const [webhook, setWebhook] = useState(""); const [clearWebhook, setClearWebhook] = useState(false); const [unbind, setUnbind] = useState(false);
  useEffect(() => { if (data) setSettings(data.settings); }, [data]);
  if (!data || !settings) return <Loading error={error} />;
  const s = settings;
  function update<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings(old => old && ({ ...old, [key]: value })); }
  function encoding<K extends keyof Settings["encoding"]>(key: K, value: Settings["encoding"][K]) { setSettings(old => old && ({ ...old, encoding: { ...old.encoding, [key]: value } })); }
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); try { const result = await api<{ encoding_changed: boolean }>("/settings", "PUT", { ...settings, webhook_secret: webhook, clear_webhook: clearWebhook, unbind_oidc: unbind }); const fresh = await api<SettingsResponse>("/settings"); setSettings(fresh.settings); setWebhook(""); setClearWebhook(false); setUnbind(false); notify(result.encoding_changed ? "notice.profileChanged" : "notice.saved"); } catch (err) { notify(err as Error, true); } finally { setBusy(false); } }
  async function bind() { try { const result = await api<{ url: string }>("/auth/oidc/bind", "POST", {}); location.href = result.url; } catch (err) { notify(err as Error, true); } }
  return <><div className="page-heading"><div><span className="eyebrow">{t("settings.eyebrow")}</span><h1>{t("app.settings")}</h1><p>{t("settings.description")}</p></div></div><form onSubmit={e => void save(e)} className="settings-form">
    <section className="panel settings-panel"><div className="settings-title"><FolderOpen /><div><h2>{t("settings.paths")}</h2><p>{t("settings.pathsHint")}</p></div></div><div className="form-grid"><Field label={t("settings.source")} hint={t("settings.sourceHint")}><input value={s.source} onChange={e => update("source", e.target.value)} required /></Field><Field label={t("settings.output")} hint={t("settings.outputHint")}><input value={s.output} onChange={e => update("output", e.target.value)} required /></Field></div><label className="check-field"><input type="checkbox" checked={s.enabled} onChange={e => update("enabled", e.target.checked)} /><span>{t("settings.enabled")}</span></label><small>{t("settings.mountHint")}</small></section>
    <section className="panel settings-panel"><div className="settings-title"><Waves /><div><h2>{t("settings.encoding")}</h2><p>{t("settings.encodingHint")}</p></div><Button type="button" variant="ghost" size="sm" onClick={() => setSettings(old => old && ({ ...old, encoding: { ...old.encoding, mode: "vbr", bitrate: 192, quality: 2 } }))}>{t("settings.restore")}</Button></div><div className="form-grid"><Field label={t("settings.codec")}><select value={s.encoding.codec} onChange={e => encoding("codec", e.target.value as "mp3" | "opus")}><option value="opus">{t("settings.opus")}</option><option value="mp3">{t("settings.mp3")}</option></select></Field><Field label={t("settings.mode")} hint={t("settings.modeHint")}><select value={s.encoding.mode} onChange={e => encoding("mode", e.target.value as "vbr" | "cbr")}><option value="vbr">{t("settings.vbr")}</option><option value="cbr">{t("settings.cbr")}</option></select></Field>{s.encoding.codec === "mp3" && s.encoding.mode === "vbr" ? <Field label={t("settings.quality")} hint={t("settings.qualityHint")}><select value={s.encoding.quality} onChange={e => encoding("quality", Number(e.target.value))}>{Array.from({ length: 10 }, (_, quality) => <option key={quality} value={quality}>V{quality}{quality === 2 ? t("settings.recommended") : ""}</option>)}</select></Field> : <Field label={s.encoding.mode === "vbr" ? t("settings.targetBitrate") : t("settings.fixedBitrate")} hint={t("settings.bitrateHint")}>{s.encoding.codec === "mp3" ? <select value={s.encoding.bitrate} onChange={e => encoding("bitrate", Number(e.target.value))}>{[32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320].map(rate => <option value={rate} key={rate}>{rate} kbps</option>)}</select> : <input type="number" min={32} max={512} value={s.encoding.bitrate} onChange={e => encoding("bitrate", Number(e.target.value))} />}</Field>}<Field label={t("settings.concurrency")} hint={t("settings.concurrencyHint")}><input type="number" min={1} max={16} value={s.concurrency} onChange={e => update("concurrency", Number(e.target.value))} /></Field><Field label={t("settings.interval")}><input type="number" min={1} max={10080} value={s.scan_minutes} onChange={e => update("scan_minutes", Number(e.target.value))} /></Field></div><div className="info-note"><Check size={15} />{t("settings.encodingNote")}</div></section>
    <section className="panel settings-panel"><div className="settings-title"><RefreshCw /><div><h2>{t("settings.integrations")}</h2><p>{t("settings.integrationsHint")}</p></div></div><div className="form-grid"><Field label={t("settings.lidarrPrefix")} hint={t("settings.lidarrPrefixHint")}><input value={s.lidarr_prefix} onChange={e => update("lidarr_prefix", e.target.value)} placeholder="/music/flac" /></Field><Field label={t("settings.webhookSecret")} hint={data.configured.webhook ? t("settings.secretConfigured") : t("settings.webhookHint")}><div className="input-action"><input type="password" value={webhook} onChange={e => setWebhook(e.target.value)} autoComplete="new-password" /><Button type="button" size="sm" variant="outline" onClick={() => { const bytes = crypto.getRandomValues(new Uint8Array(24)); const secret = Array.from(bytes, b => b.toString(16).padStart(2, "0")).join(""); setWebhook(secret); void navigator.clipboard?.writeText(secret).then(() => notify("notice.secretCopied")).catch(() => notify("notice.copyFailed", true)); }}>{t("settings.generate")}</Button></div></Field></div><label className="check-field"><input type="checkbox" checked={clearWebhook} onChange={e => setClearWebhook(e.target.checked)} />{t("settings.disableWebhook")}</label><div className="endpoint"><code>POST /api/webhook/lidarr</code><span>{t("settings.webhookCredentials")}</span></div><div className="form-grid mt-6"><Field label={t("settings.navUrl")}><input type="url" value={s.nav_url} onChange={e => update("nav_url", e.target.value)} placeholder="http://navidrome:4533" /></Field><Field label={t("settings.navLibrary")}><input type="number" min={1} value={s.nav_library} onChange={e => update("nav_library", Number(e.target.value))} /></Field><Field label={t("settings.navUser")}><input value={s.nav_user} onChange={e => update("nav_user", e.target.value)} autoComplete="off" /></Field><Field label={t("settings.navPassword")} hint={data.configured.nav_password ? t("settings.keepSecret") : undefined}><input type="password" value={s.nav_password || ""} onChange={e => update("nav_password", e.target.value)} autoComplete="new-password" /></Field></div><Button type="button" variant="outline" size="sm" onClick={() => void api("/navidrome/refresh", "POST", {}).then(() => notify("notice.refresh")).catch(err => notify(err as Error, true))}>{t("settings.refresh")}</Button><small>{t("settings.navHint")}</small></section>
    <section className="panel settings-panel"><div className="settings-title"><ShieldCheck /><div><h2>{t("settings.oidc")}</h2><p>{t("settings.oidcHint")}</p></div></div><div className="form-grid"><Field label={t("settings.issuer")}><input type="url" value={s.oidc_issuer} onChange={e => update("oidc_issuer", e.target.value)} placeholder="https://auth.example.com/application/o/musicforge/" /></Field><Field label={t("settings.clientId")}><input value={s.oidc_client_id} onChange={e => update("oidc_client_id", e.target.value)} /></Field><Field label={t("settings.clientSecret")} hint={data.configured.oidc_secret ? t("settings.keepSecret") : undefined}><input type="password" value={s.oidc_secret || ""} onChange={e => update("oidc_secret", e.target.value)} autoComplete="new-password" /></Field><Field label={t("settings.callback")}><input readOnly value={data.public_url ? `${data.public_url}/api/auth/oidc/callback` : t("settings.publicUrlFirst")} /></Field></div>{s.bound_subject && <div className="info-note"><Check size={16} />{t("settings.bound", { identity: s.bound_username || s.bound_email || s.bound_subject })}</div>}<div className="actions"><Button type="button" variant="outline" disabled={me.method !== "local"} onClick={() => void bind()}>{t("settings.bind")}</Button><label className="check-field"><input type="checkbox" checked={unbind} onChange={e => setUnbind(e.target.checked)} />{t("settings.unbind")}</label></div><small>{t("settings.bindHint")}</small></section>
    <div className="settings-save"><span>{t("settings.savedIn")}</span><Button disabled={busy}>{busy ? <Loader2 size={16} className="animate-spin" /> : <Check size={16} />}{t("settings.save")}</Button></div>
  </form><PasswordForm notify={notify} disabled={me.method !== "local"} /></>;
}

function PasswordForm({ notify, disabled }: { notify: Notice; disabled: boolean }) {
  const { t } = useI18n();
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const element = e.currentTarget; const form = new FormData(element); try { await api("/auth/password", "POST", { current: form.get("current"), password: form.get("password") }); const me = await api<Me>("/auth/me"); setCSRF(me.csrf || ""); notify("notice.password"); element.reset(); } catch (err) { notify(err as Error, true); } }
  return <form className="panel settings-panel mt-6" onSubmit={e => void submit(e)}><div className="settings-title"><ShieldCheck /><div><h2>{t("password.title")}</h2><p>{t("password.description")}</p></div></div><div className="form-grid"><Field label={t("password.current")}><input name="current" type="password" required disabled={disabled} autoComplete="current-password" /></Field><Field label={t("password.new")} hint={t("auth.passwordHint")}><input name="password" type="password" required disabled={disabled} autoComplete="new-password" /></Field></div><Button variant="outline" disabled={disabled}>{t("password.update")}</Button></form>;
}
