import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Activity, ArrowDownToLine, ArrowRight, Check, ChevronLeft, ChevronRight, Clock3, Disc3, FolderOpen, HardDrive, LayoutDashboard, ListMusic, Loader2, LogOut, Music2, Play, RefreshCw, Search, Settings2, ShieldCheck, Trash2, Waves } from "lucide-react";
import { Button } from "./components/ui/button";
import { api, setCSRF } from "./api";
import type { Dashboard, Job, Me, Settings, Source } from "./types";

type Notice = (message: string, error?: boolean) => void;
const statuses: Record<string, string> = { ready: "已就绪", expired: "过期 · 源已删除", needs_rebuild: "待重建", missing: "待生成 / 输出缺失", changed: "源已变化", failed: "失败", pending: "等待中", running: "运行中", success: "成功" };
const kinds: Record<string, string> = { scan: "扫描音乐库", convert: "音频转换", move: "搬迁产物", delete: "删除过期产物", upgrade: "升级替换清理", refresh: "刷新 Navidrome" };
const date = (value: number) => new Date(value * 1000).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" });

function useResource<T>(path: string, poll = false) {
  const [data, setData] = useState<T>();
  const [error, setError] = useState("");
  useEffect(() => {
    let alive = true;
    const load = () => api<T>(path).then(value => { if (alive) { setData(value); setError(""); } }).catch(err => { if (alive) setError(String(err.message)); });
    void load();
    const timer = poll ? setInterval(load, 5000) : undefined;
    return () => { alive = false; clearInterval(timer); };
  }, [path, poll]);
  return { data, error };
}
function Badge({ status }: { status: string }) { return <span className={`badge badge-${status}`}><span />{statuses[status] || status}</span>; }
function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="empty"><Disc3 size={36} strokeWidth={1.2} /><h3>{title}</h3><p>{children}</p></div>; }
function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <div className="field"><label className="field-label"><span>{label}</span>{children}</label>{hint && <small>{hint}</small>}</div>; }
function Loading({ error }: { error?: string }) { return <div className="empty">{error ? <p role="alert">{error}</p> : <Loader2 className="animate-spin" />}</div>; }

export function App() {
  const [me, setMe] = useState<Me>();
  const [authError, setAuthError] = useState("");
  const [page, setPage] = useState(location.pathname);
  const [toast, setToast] = useState<{ message: string; error: boolean }>();
  const notify: Notice = (message, error = false) => setToast({ message, error });
  const loadMe = () => api<Me>("/auth/me").then(value => { setCSRF(value.csrf || ""); setMe(value); setAuthError(""); }).catch(err => setAuthError(err.message));
  useEffect(() => {
    void loadMe();
    const pop = () => setPage(location.pathname);
    const expired = () => { setMe(undefined); void loadMe(); };
    window.addEventListener("popstate", pop); window.addEventListener("session-expired", expired);
    return () => { window.removeEventListener("popstate", pop); window.removeEventListener("session-expired", expired); };
  }, []);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(undefined), 6000); return () => clearTimeout(timer); } }, [toast]);
  function navigate(path: string) { history.pushState(null, "", path); setPage(path); window.scrollTo(0, 0); }
  if (!me) return <div className="auth-layout"><Loading error={authError} />{authError && <Button onClick={() => void loadMe()}>重新连接</Button>}</div>;
  if (!me.authenticated) return <Auth me={me} done={loadMe} />;
  const nav = [{ path: "/", label: "概览", icon: LayoutDashboard }, { path: "/library", label: "音乐库", icon: ListMusic }, { path: "/jobs", label: "任务", icon: Activity }, { path: "/settings", label: "设置", icon: Settings2 }];
  const current = nav.find(item => item.path === page) || nav[0];
  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="/" onClick={e => { e.preventDefault(); navigate("/"); }}><span className="brand-icon"><Waves /></span><span>MusicForge<small>FLAC → STREAMING</small></span></a>
      <span className="nav-caption">工作空间</span>
      <nav aria-label="主导航">{nav.map(item => <a key={item.path} href={item.path} className={current.path === item.path ? "active" : ""} onClick={e => { e.preventDefault(); navigate(item.path); }}><item.icon size={19} />{item.label}{current.path === item.path && <span className="nav-dot" />}</a>)}</nav>
      <div className="sidebar-bottom"><div className="single-host"><HardDrive size={16} /><span>单机音乐构建<small>{me.version}</small></span></div><div className="account"><span className="avatar">{me.username?.slice(0, 1).toUpperCase()}</span><span>{me.username}<small>{me.method === "oidc" ? "OIDC 管理员" : "本地管理员"}</small></span><Button variant="ghost" size="icon" aria-label="退出登录" onClick={() => void api("/auth/logout", "POST", {}).then(loadMe).catch(err => notify(err.message, true))}><LogOut size={17} /></Button></div></div>
    </aside>
    <main className="main"><header className="topbar"><span>工作空间 <ChevronRight size={14} /> <strong>{current.label}</strong></span><span className="topbar-note"><ShieldCheck size={15} /> 管理员会话</span></header>
      <div className="page-content">{page === "/library" ? <Library notify={notify} /> : page === "/jobs" ? <Jobs notify={notify} /> : page === "/settings" ? <SettingsPage me={me} notify={notify} /> : <Overview notify={notify} navigate={navigate} />}</div>
    </main>
    {toast && <div className={`toast ${toast.error ? "toast-error" : ""}`} role={toast.error ? "alert" : "status"}>{toast.error ? <Activity size={17} /> : <Check size={17} />}{toast.message}<button aria-label="关闭通知" onClick={() => setToast(undefined)}>×</button></div>}
  </div>;
}

function Auth({ me, done }: { me: Me; done: () => Promise<void> }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const setup = !me.initialized;
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(""); const form = new FormData(e.currentTarget); try { await api(`/auth/${setup ? "setup" : "login"}`, "POST", { username: form.get("username"), password: form.get("password"), ...(setup ? { code: form.get("code") } : {}) }); await done(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  return <div className="auth-layout"><div className="auth-art" aria-hidden="true">{Array.from({ length: 29 }, (_, i) => <span key={i} style={{ height: `${20 + Math.sin(i * 1.7) ** 2 * 130}px` }} />)}</div><div className="auth-card"><div className="auth-logo"><Waves size={30} /> MusicForge</div><span className="eyebrow">YOUR MUSIC, READY TO STREAM</span><h1>{setup ? "创建你的音乐工作空间" : "欢迎回来"}</h1><p>{setup ? "从容器启动日志获取初始化码，创建唯一管理员账号。" : "登录后管理无损母库与流媒体版本。"}</p>
    <form onSubmit={submit}>{setup && <Field label="初始化码"><input name="code" required autoComplete="off" placeholder="容器日志中的 setup_code" /></Field>}<Field label="用户名"><input name="username" required autoComplete="username" maxLength={100} /></Field><Field label="密码" hint={setup ? "至少 12 个字符，最多 72 字节。" : undefined}><input name="password" type="password" required minLength={setup ? 12 : undefined} autoComplete={setup ? "new-password" : "current-password"} /></Field>{error && <div className="error-box" role="alert">{error}</div>}<Button className="w-full" disabled={busy}>{busy ? <Loader2 size={16} className="animate-spin" /> : <ArrowRight size={16} />}{setup ? "创建管理员" : "登录"}</Button></form>{!setup && me.oidc && <Button className="mt-3 w-full" variant="outline" asChild><a href="/api/auth/oidc/login"><ShieldCheck size={17} />使用 OIDC 登录</a></Button>}<small className="auth-footer">无损源库 · 增量构建 · 自托管</small></div></div>;
}

function Overview({ notify, navigate }: { notify: Notice; navigate: (path: string) => void }) {
  const { data, error } = useResource<Dashboard>("/dashboard", true);
  const jobs = useResource<{ jobs: Job[] }>("/jobs?limit=5", true);
  const config = useResource<{ settings: Settings }>("/settings");
  const [busy, setBusy] = useState(false);
  async function scan() { setBusy(true); try { await api("/library/scan", "POST", {}); notify("扫描已加入队列"); } catch (err) { notify((err as Error).message, true); } finally { setBusy(false); } }
  if (!data) return <Loading error={error} />;
  const percent = data.source_count ? Math.round(data.ready_count / data.source_count * 100) : 0;
  const metrics = [{ label: "FLAC 源文件", value: data.source_count, icon: Disc3, note: "无损母库" }, { label: "流媒体产物", value: data.output_count, icon: Music2, note: `${data.codec.toUpperCase()} 输出库` }, { label: "构建完成", value: `${percent}%`, icon: Check, note: `${data.ready_count.toLocaleString()} 首符合当前配置` }, { label: "待处理", value: data.expired_count + data.rebuild_count, icon: Clock3, note: `${data.rebuild_count} 待重建 · ${data.expired_count} 过期` }];
  return <><div className="page-heading"><div><span className="eyebrow">LIBRARY OVERVIEW</span><h1>音乐，从母库到播放</h1><p>让无损收藏始终拥有一份轻量的流媒体版本。</p></div><Button onClick={() => void scan()} disabled={busy || !data.enabled}><RefreshCw size={16} className={busy ? "animate-spin" : ""} />扫描音乐库</Button></div>
    {!data.online && <div className="banner"><HardDrive size={20} /><div><strong>{data.enabled ? "音乐存储离线，任务已暂停" : "配置音乐库，开始第一次构建"}</strong><p>{data.storage_message}</p></div><Button variant="outline" size="sm" onClick={() => navigate("/settings")}>打开设置</Button></div>}
    {data.rebuild_count > 0 && <div className="banner"><RefreshCw size={20} /><div><strong>{data.rebuild_count} 首歌曲等待按新配置重建</strong><p>已有产物继续保留，手动启动后才会替换。</p></div><Button variant="outline" size="sm" onClick={() => navigate("/library")}>查看音乐库</Button></div>}
    <div className="metrics">{metrics.map(metric => <div className="metric" key={metric.label}><div><span>{metric.label}</span><metric.icon size={19} /></div><strong>{typeof metric.value === "number" ? metric.value.toLocaleString() : metric.value}</strong><small>{metric.note}</small></div>)}</div>
    <div className="panel pipeline"><div className="panel-heading"><div><h2>你的音乐流水线</h2><p>源文件驱动构建，产物交给播放器。</p></div><span className={`online ${data.online ? "is-online" : ""}`}><span />{data.online ? "存储在线" : "等待存储"}</span></div><div className="pipeline-flow"><div><Disc3 /><small>SOURCE OF TRUTH</small><h3>FLAC 母库</h3><code>{config.data?.settings.source || "—"}</code></div><ArrowRight className="flow-arrow" /><div className="pipeline-forge"><Waves /><small>INCREMENTAL BUILD</small><h3>MusicForge</h3><span>ffmpeg · {data.codec.toUpperCase()}</span></div><ArrowRight className="flow-arrow" /><div><ArrowDownToLine /><small>GENERATED ARTIFACTS</small><h3>流媒体库</h3><code>{config.data?.settings.output || "—"}</code></div></div><div className="build-progress"><span>符合当前构建配置</span><span>{data.ready_count} / {data.source_count}</span><div><span style={{ width: `${percent}%` }} /></div></div></div>
    <div className="panel"><div className="panel-heading"><div><h2>最近任务</h2><p>后台处理，不影响你的音乐播放。</p></div><Button variant="ghost" size="sm" onClick={() => navigate("/jobs")}>全部任务 <ArrowRight size={14} /></Button></div>{jobs.data?.jobs.length ? <div className="job-list">{jobs.data.jobs.map(job => <div className="job-row" key={job.id}><span className={`job-symbol ${job.state}`}><Activity size={18} /></span><div><strong>{kinds[job.kind] || job.kind}</strong><small>任务 #{job.id} · {date(job.updated)}</small></div><Badge status={job.state} /></div>)}</div> : <Empty title="还没有任务">启用音乐库并扫描后，任务将显示在这里。</Empty>}</div>
  </>;
}

function Library({ notify }: { notify: Notice }) {
  const { data, error } = useResource<Source[]>("/library", true);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState<Set<number>>(new Set()); const [busy, setBusy] = useState(false); const [offset, setOffset] = useState(0);
  async function action(path: string, body: unknown, message: string) { setBusy(true); try { await api(path, "POST", body); notify(message); setSelected(new Set()); } catch (err) { notify((err as Error).message, true); } finally { setBusy(false); } }
  if (!data) return <Loading error={error} />;
  const rows = data.filter(source => (filter === "all" || source.status === filter) && `${source.artist} ${source.album} ${source.title} ${source.path}`.toLowerCase().includes(query.toLowerCase()));
  const shown = rows.slice(offset, offset + 50); const expired = data.filter(s => !s.present && s.output).length;
  function toggle(id: number) { setSelected(old => { const value = new Set(old); if (value.has(id)) value.delete(id); else value.add(id); return value; }); }
  function deleteSelected(all: boolean) { if (window.confirm(all ? `永久删除全部 ${expired} 首过期产物？源文件不会被修改。` : "永久删除所选歌曲中的过期产物？")) void action("/library/delete", { all, ids: [...selected] }, "删除任务已加入队列，完成后会刷新 Navidrome"); }
  return <><div className="page-heading"><div><span className="eyebrow">LIBRARY</span><h1>音乐库</h1><p>{data.length.toLocaleString()} 首索引歌曲 · 源与产物状态一目了然</p></div><div className="actions"><Button variant="outline" disabled={busy} onClick={() => void action("/library/scan", { verify: true }, "完整哈希校验已加入队列")}><ShieldCheck size={16} />完整校验</Button><Button disabled={busy} onClick={() => void action("/library/scan", {}, "扫描已加入队列")}><RefreshCw size={16} />扫描</Button></div></div>
    {expired > 0 && <div className="banner amber"><Clock3 size={20} /><div><strong>{expired} 首过期产物仍保留在播放库</strong><p>源文件已删除。手动删除产物后，Navidrome 会移除相应歌曲。</p></div><Button variant="destructive" size="sm" disabled={busy} onClick={() => deleteSelected(true)}>批量删除过期</Button></div>}
    <div className="panel"><div className="table-toolbar"><div className="search"><Search size={17} /><input aria-label="搜索音乐库" placeholder="搜索艺人、专辑、歌曲或路径…" value={query} onChange={e => { setQuery(e.target.value); setOffset(0); }} /></div><select aria-label="状态筛选" value={filter} onChange={e => { setFilter(e.target.value); setOffset(0); }}><option value="all">全部状态</option>{["ready", "needs_rebuild", "expired", "missing", "changed", "failed"].map(status => <option value={status} key={status}>{statuses[status]}</option>)}</select><Button variant="outline" size="sm" disabled={busy} onClick={() => void action("/library/rebuild", { all: true }, "待生成与待重建歌曲已加入队列")}><Play size={14} />启动待重建</Button></div>
      {selected.size > 0 && <div className="selection-bar"><span>已选择 {selected.size} 首</span><Button size="sm" variant="outline" disabled={busy} onClick={() => void action("/library/rebuild", { ids: [...selected] }, "所选歌曲已加入构建队列")}>构建所选</Button><Button size="sm" variant="destructive" disabled={busy} onClick={() => deleteSelected(false)}><Trash2 size={13} />删除所选过期产物</Button><Button size="sm" variant="ghost" onClick={() => setSelected(new Set())}>取消选择</Button></div>}
      {rows.length ? <><div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="选择当前页" checked={shown.length > 0 && shown.every(s => selected.has(s.id))} onChange={e => setSelected(old => { const value = new Set(old); shown.forEach(s => e.target.checked ? value.add(s.id) : value.delete(s.id)); return value; })} /></th><th>歌曲 / 文件</th><th>艺人 / 专辑</th><th>源文件</th><th>产物状态</th></tr></thead><tbody>{shown.map(source => <tr key={source.id} className={selected.has(source.id) ? "selected" : ""}><td><input type="checkbox" aria-label={`选择 ${source.title || source.path}`} checked={selected.has(source.id)} onChange={() => toggle(source.id)} /></td><td><div className="track-cell"><span className="track-number">{source.track || <Music2 size={15} />}</span><div><strong>{source.title || source.path.split("/").pop()}</strong><small title={source.path}>{source.path}</small></div></div></td><td><strong>{source.artist || "未知艺人"}</strong><small>{source.album || "未知专辑"}</small></td><td><span className={source.present ? "source-present" : "source-missing"}>{source.present ? "FLAC · 在线" : "源已删除"}</span></td><td><Badge status={source.status} />{source.output_present && source.status !== "ready" && <small>已有产物仍可播放</small>}{source.error && <details><summary>错误详情</summary><pre>{source.error}</pre></details>}</td></tr>)}</tbody></table></div><div className="pagination"><span>显示 {offset + 1}–{Math.min(offset + 50, rows.length)} / {rows.length}</span><Button variant="ghost" size="icon" aria-label="上一页" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}><ChevronLeft size={16} /></Button><Button variant="ghost" size="icon" aria-label="下一页" disabled={offset + 50 >= rows.length} onClick={() => setOffset(offset + 50)}><ChevronRight size={16} /></Button></div></> : <Empty title={data.length ? "没有匹配的歌曲" : "音乐库还是空的"}>{data.length ? "尝试调整搜索词或状态筛选。" : "在设置中启用音乐库，然后扫描 FLAC 源目录。"}</Empty>}
    </div></>;
}

function Jobs({ notify }: { notify: Notice }) {
  const [offset, setOffset] = useState(0); const [filter, setFilter] = useState("all"); const [expanded, setExpanded] = useState<number>(); const [selected, setSelected] = useState<Set<number>>(new Set());
  const { data, error } = useResource<{ jobs: Job[]; total: number }>(`/jobs?offset=${offset}&limit=100`, true);
  async function retry(ids?: number[]) { try { await api("/jobs/retry", "POST", ids ? { ids } : { all: true }); notify("失败任务已重新排队"); setSelected(new Set()); } catch (err) { notify((err as Error).message, true); } }
  if (!data) return <Loading error={error} />;
  const shown = data.jobs.filter(job => filter === "all" || job.state === filter);
  return <><div className="page-heading"><div><span className="eyebrow">BUILD QUEUE</span><h1>后台任务</h1><p>持久化队列 · 自动重试两次 · 中断后自动恢复</p></div><Button variant="outline" onClick={() => void retry()}><RefreshCw size={16} />重试全部失败</Button></div><div className="panel"><div className="table-toolbar"><div className="filter-tabs">{["all", "pending", "running", "success", "failed"].map(state => <button key={state} className={filter === state ? "active" : ""} onClick={() => setFilter(state)}>{state === "all" ? "全部" : statuses[state]}</button>)}</div>{selected.size > 0 && <Button size="sm" onClick={() => void retry([...selected])}>重试所选 {selected.size} 项</Button>}</div>{shown.length ? <div className="task-list">{shown.map(job => <div className="task" key={job.id}><div className="task-main"><input type="checkbox" aria-label={`选择失败任务 ${job.id}`} disabled={job.state !== "failed"} checked={selected.has(job.id)} onChange={e => setSelected(old => { const value = new Set(old); e.target.checked ? value.add(job.id) : value.delete(job.id); return value; })} /><span className={`job-symbol ${job.state}`}>{job.state === "running" ? <Loader2 className="animate-spin" size={18} /> : <Activity size={18} />}</span><div className="task-description"><strong>{kinds[job.kind]} <span>#{job.id}</span></strong><small>{job.args.id ? `歌曲 #${job.args.id} · ` : ""}{date(job.updated)} · 失败尝试 {job.attempts}/3</small></div><Badge status={job.state} /><Button variant="ghost" size="sm" onClick={() => setExpanded(expanded === job.id ? undefined : job.id)}>{expanded === job.id ? "收起" : "详情"}</Button>{job.state === "failed" && <Button variant="outline" size="sm" onClick={() => void retry([job.id])}>重试</Button>}</div>{expanded === job.id && <div className="task-details"><p>请求参数</p><pre>{JSON.stringify(job.args, null, 2)}</pre><p>任务日志</p><pre>{job.log || (job.state === "success" ? "任务成功完成。" : job.state === "running" ? "后台处理中；日志将在任务完成或失败时更新。" : "等待 worker 执行。")}</pre></div>}</div>)}</div> : <Empty title="此页没有匹配任务">任务会在扫描或构建时自动创建。</Empty>}<div className="pagination"><span>{data.total} 项历史任务</span><Button variant="ghost" size="icon" aria-label="上一页任务" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 100))}><ChevronLeft size={16} /></Button><Button variant="ghost" size="icon" aria-label="下一页任务" disabled={offset + 100 >= data.total} onClick={() => setOffset(offset + 100)}><ChevronRight size={16} /></Button></div></div></>;
}

type SettingsResponse = { settings: Settings; configured: { webhook: boolean; nav_password: boolean; oidc_secret: boolean }; public_url: string };
function SettingsPage({ me, notify }: { me: Me; notify: Notice }) {
  const { data, error } = useResource<SettingsResponse>("/settings");
  const [settings, setSettings] = useState<Settings>(); const [busy, setBusy] = useState(false); const [webhook, setWebhook] = useState(""); const [clearWebhook, setClearWebhook] = useState(false); const [unbind, setUnbind] = useState(false);
  useEffect(() => { if (data) setSettings(data.settings); }, [data]);
  if (!data || !settings) return <Loading error={error} />;
  const s = settings;
  function update<K extends keyof Settings>(key: K, value: Settings[K]) { setSettings(old => old && ({ ...old, [key]: value })); }
  function encoding<K extends keyof Settings["encoding"]>(key: K, value: Settings["encoding"][K]) { setSettings(old => old && ({ ...old, encoding: { ...old.encoding, [key]: value } })); }
  async function save(e: FormEvent) { e.preventDefault(); setBusy(true); try { const result = await api<{ encoding_changed: boolean }>("/settings", "PUT", { ...settings, webhook_secret: webhook, clear_webhook: clearWebhook, unbind_oidc: unbind }); const fresh = await api<SettingsResponse>("/settings"); setSettings(fresh.settings); setWebhook(""); setClearWebhook(false); setUnbind(false); notify(result.encoding_changed ? "设置已保存。现有产物已标记待重建，请到音乐库手动启动。" : "设置已保存"); } catch (err) { notify((err as Error).message, true); } finally { setBusy(false); } }
  async function bind() { try { const result = await api<{ url: string }>("/auth/oidc/bind", "POST", {}); location.href = result.url; } catch (err) { notify((err as Error).message, true); } }
  return <><div className="page-heading"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h1>设置</h1><p>一份源库，一份产物库，一套构建配置。</p></div></div><form onSubmit={e => void save(e)} className="settings-form">
    <section className="panel settings-panel"><div className="settings-title"><FolderOpen /><div><h2>音乐库路径</h2><p>使用容器内路径。输出目录首次启用时必须为空。</p></div></div><div className="form-grid"><Field label="FLAC 源目录" hint="只读挂载；MusicForge 不修改源文件。"><input value={s.source} onChange={e => update("source", e.target.value)} required /></Field><Field label="转码输出目录" hint="读写挂载；Navidrome 建议只读挂载此目录。"><input value={s.output} onChange={e => update("output", e.target.value)} required /></Field></div><label className="check-field"><input type="checkbox" checked={s.enabled} onChange={e => update("enabled", e.target.checked)} /><span>启用音乐库扫描和后台任务</span></label><small>索引后保持容器内根路径稳定。挂载变化后，核对目录并保存设置以确认新挂载。</small></section>
    <section className="panel settings-panel"><div className="settings-title"><Waves /><div><h2>编码配置</h2><p>调整配置后标记待重建，已有文件继续可播放。</p></div><Button type="button" variant="ghost" size="sm" onClick={() => setSettings(old => old && ({ ...old, encoding: { ...old.encoding, mode: "vbr", bitrate: 192, quality: 2 } }))}>恢复推荐值</Button></div><div className="form-grid"><Field label="输出格式"><select value={s.encoding.codec} onChange={e => encoding("codec", e.target.value as "mp3" | "opus")}><option value="opus">Opus · 推荐</option><option value="mp3">MP3 · 广泛兼容</option></select></Field><Field label="码率模式" hint="VBR 随音频复杂度分配码率；CBR 使用固定码率。"><select value={s.encoding.mode} onChange={e => encoding("mode", e.target.value as "vbr" | "cbr")}><option value="vbr">VBR · 可变码率（推荐）</option><option value="cbr">CBR · 固定码率</option></select></Field>{s.encoding.codec === "mp3" && s.encoding.mode === "vbr" ? <Field label="MP3 VBR 质量" hint="推荐 V2，通常约 190kbps；V0 质量最高，V9 最低。"><select value={s.encoding.quality} onChange={e => encoding("quality", Number(e.target.value))}>{Array.from({ length: 10 }, (_, quality) => <option key={quality} value={quality}>V{quality}{quality === 2 ? " · 推荐" : ""}</option>)}</select></Field> : <Field label={s.encoding.mode === "vbr" ? "平均目标码率 (kbps)" : "固定码率 (kbps)"} hint="推荐 192kbps。">{s.encoding.codec === "mp3" ? <select value={s.encoding.bitrate} onChange={e => encoding("bitrate", Number(e.target.value))}>{[32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320].map(rate => <option value={rate} key={rate}>{rate} kbps</option>)}</select> : <input type="number" min={32} max={512} value={s.encoding.bitrate} onChange={e => encoding("bitrate", Number(e.target.value))} />}</Field>}<Field label="同时转换数量" hint="默认 1；提高并发会增加 CPU 和磁盘负载。"><input type="number" min={1} max={16} value={s.concurrency} onChange={e => update("concurrency", Number(e.target.value))} /></Field><Field label="扫描间隔（分钟）"><input type="number" min={1} max={10080} value={s.scan_minutes} onChange={e => update("scan_minutes", Number(e.target.value))} /></Field></div><div className="info-note"><Check size={15} />保留标签与 ReplayGain · 专辑共用 cover.jpg · 新文件验证后替换</div></section>
    <section className="panel settings-panel"><div className="settings-title"><RefreshCw /><div><h2>Lidarr 与 Navidrome</h2><p>升级事件驱动构建，任务批次结束后刷新播放库。</p></div></div><div className="form-grid"><Field label="Lidarr 源路径前缀" hint="Lidarr 看到的 FLAC 根目录，留空表示与 MusicForge 路径一致。"><input value={s.lidarr_prefix} onChange={e => update("lidarr_prefix", e.target.value)} placeholder="/music/flac" /></Field><Field label="Webhook 独立密钥" hint={data.configured.webhook ? "已配置。留空保留现有密钥。" : "至少 24 个字符；仅用于触发扫描。"}><div className="input-action"><input type="password" value={webhook} onChange={e => setWebhook(e.target.value)} autoComplete="new-password" /><Button type="button" size="sm" variant="outline" onClick={() => { const bytes = crypto.getRandomValues(new Uint8Array(24)); const secret = Array.from(bytes, b => b.toString(16).padStart(2, "0")).join(""); setWebhook(secret); void navigator.clipboard?.writeText(secret).then(() => notify("新密钥已复制，请保存设置后填入 Lidarr")).catch(() => notify("复制失败，请重新输入自选密钥", true)); }}>生成并复制</Button></div></Field></div><label className="check-field"><input type="checkbox" checked={clearWebhook} onChange={e => setClearWebhook(e.target.checked)} />禁用现有 webhook 密钥</label><div className="endpoint"><code>POST /api/webhook/lidarr</code><span>Lidarr Webhook：Username = musicforge，Password = 独立密钥</span></div><div className="form-grid mt-6"><Field label="Navidrome 地址"><input type="url" value={s.nav_url} onChange={e => update("nav_url", e.target.value)} placeholder="http://navidrome:4533" /></Field><Field label="Navidrome 音乐库 ID"><input type="number" min={1} value={s.nav_library} onChange={e => update("nav_library", Number(e.target.value))} /></Field><Field label="Navidrome 用户名"><input value={s.nav_user} onChange={e => update("nav_user", e.target.value)} autoComplete="off" /></Field><Field label="Navidrome 密码" hint={data.configured.nav_password ? "已配置；留空保留。" : undefined}><input type="password" value={s.nav_password || ""} onChange={e => update("nav_password", e.target.value)} autoComplete="new-password" /></Field></div><Button type="button" variant="outline" size="sm" onClick={() => void api("/navidrome/refresh", "POST", {}).then(() => notify("Navidrome 刷新已加入队列；使用已保存的设置")).catch(err => notify(err.message, true))}>手动刷新 Navidrome</Button><small>Navidrome 0.59.0+ 定向扫描专辑目录；旧版本使用普通扫描。</small></section>
    <section className="panel settings-panel"><div className="settings-title"><ShieldCheck /><div><h2>OIDC 登录</h2><p>只允许绑定的一个管理员身份。保留本地密码作为恢复方式。</p></div></div><div className="form-grid"><Field label="Issuer URL"><input type="url" value={s.oidc_issuer} onChange={e => update("oidc_issuer", e.target.value)} placeholder="https://auth.example.com/application/o/musicforge/" /></Field><Field label="Client ID"><input value={s.oidc_client_id} onChange={e => update("oidc_client_id", e.target.value)} /></Field><Field label="Client Secret" hint={data.configured.oidc_secret ? "已配置；留空保留。" : undefined}><input type="password" value={s.oidc_secret || ""} onChange={e => update("oidc_secret", e.target.value)} autoComplete="new-password" /></Field><Field label="回调地址"><input readOnly value={data.public_url ? `${data.public_url}/api/auth/oidc/callback` : "先配置 MUSICFORGE_PUBLIC_URL"} /></Field></div>{s.bound_subject && <div className="info-note"><Check size={16} />已绑定：{s.bound_username || s.bound_email || s.bound_subject}</div>}<div className="actions"><Button type="button" variant="outline" disabled={me.method !== "local"} onClick={() => void bind()}>绑定当前 OIDC 身份</Button><label className="check-field"><input type="checkbox" checked={unbind} onChange={e => setUnbind(e.target.checked)} />解除现有绑定</label></div><small>先保存 OIDC 设置，再用本地管理员会话完成绑定。</small></section>
    <div className="settings-save"><span>设置保存在 /config 的 SQLite 数据库中</span><Button disabled={busy}>{busy ? <Loader2 size={16} className="animate-spin" /> : <Check size={16} />}保存设置</Button></div>
  </form><PasswordForm notify={notify} disabled={me.method !== "local"} /></>;
}

function PasswordForm({ notify, disabled }: { notify: Notice; disabled: boolean }) {
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const element = e.currentTarget; const form = new FormData(element); try { await api("/auth/password", "POST", { current: form.get("current"), password: form.get("password") }); const me = await api<Me>("/auth/me"); setCSRF(me.csrf || ""); notify("密码已更新，其他会话已退出"); element.reset(); } catch (err) { notify((err as Error).message, true); } }
  return <form className="panel settings-panel mt-6" onSubmit={e => void submit(e)}><div className="settings-title"><ShieldCheck /><div><h2>本地管理员密码</h2><p>修改密码会撤销其他登录会话。</p></div></div><div className="form-grid"><Field label="当前密码"><input name="current" type="password" required disabled={disabled} autoComplete="current-password" /></Field><Field label="新密码"><input name="password" type="password" required minLength={12} disabled={disabled} autoComplete="new-password" /></Field></div><Button variant="outline" disabled={disabled}>更新密码</Button></form>;
}
